[package]
name = "seqset"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mibmo/seqset"
description = "Efficient iterator sequence based on charset"
